### ISSUE TITLE
999 limit?

### ISSUE THREAD

**Issue by domdee7** [notsatan/kodi-strm#241]
### Actual total folder size and objects

> ![image](https://user-images.githubusercontent.com/101055365/156930407-86f66706-8f8f-4296-92cd-727b0de2adad.png)

### Generated .strm to 999 items only

> ![image](https://user-images.githubusercontent.com/101055365/156930213-afad1a19-bcb8-48a6-ad14-bf0deb9a9a23.png)

I had this issue since the early versions, but proceeds to use the Kodi addon instead. Now I did a clean install there and generating .strm is still super slow, then I remembered this script.

_Just created a GitHub account to report this! 😁_

**Comment by notsatan** [comment]
There is no such limit on the number of strm files that can be generated. I remember using `kodi-strm` to generate ~5k files during a stress-test

To help me better debug the issue, please answer the following
1. How did you get a count of the number of items in the directory (looks like [`rclone`][rclone], but would like a confirmation regardless).
2. What is the output of `python strm-generator.py --version`
3. Can you verify that the source folder you're using is the **same** as the same directory you're scanning for the file count?
4. Where are those files located (team drive, personal drive)?
5. Who owns those files (as in, Google account), and is that the same account you used to login for `kodi-strm`?
6. Can you verify that those files/directories are not flagged?

[rclone]: https://github.com/rclone/rclone

**Comment by notsatan** [comment]
The script cannot *skip* files[1] provided by the API 

https://github.com/notsatan/kodi-strm/blob/c3ca99b0233a1bab189538de69868af02b1713e9/src/drive_handler.py#L249-L266

Which leads me to believe that the problem could be with the Google Drive API not returning those files (especially for files flagged for abuse), or the file count from the first screenshot belongs to some other directory.

[1]: Unintentionally, at least. Files that are deliberately skipped, will increment the *"Files Skipped"* counter

**Comment by domdee7** [comment]
> There is no such limit on the number of strm files that can be generated. I remember using `kodi-strm` to generate ~5k files during a stress-test
> 
> To help me better debug the issue, please answer the following
> 
> 1. How did you get a count of the number of items in the directory (looks like [`rclone`](https://github.com/rclone/rclone), but would like a confirmation regardless).
> 2. What is the output of `python strm-generator.py --version`
> 3. Can you verify that the source folder you're using is the **same** as the same directory you're scanning for the file count?
> 4. Where are those files located (team drive, personal drive)?
> 5. Who owns those files (as in, Google account), and is that the same account you used to login for `kodi-strm`?
> 6. Can you verify that those files/directories are not flagged?

1. Yes, it's Rclone
2. ![image](https://user-images.githubusercontent.com/101055365/157069703-84240cf5-aba5-4902-a22d-22da8adea045.png)
3. They're the same, even scanning the whole drive itself since there's only one folder, generates only 999 inside
4. Shared/Team Drive
5. Owned the files uploaded. The same account logged in.
6. Not sure how, but on the Kodi add-on when checking files for flags, I've encountered none so far.

**Comment by domdee7** [comment]
> The script cannot _skip_ files[1] provided by the API
> 
> https://github.com/notsatan/kodi-strm/blob/c3ca99b0233a1bab189538de69868af02b1713e9/src/drive_handler.py#L249-L266
> 
> Which leads me to believe that the problem could be with the Google Drive API not returning those files (especially for files flagged for abuse), or the file count from the first screenshot belongs to some other directory.
> 
> [1]: Unintentionally, at least. Files that are deliberately skipped, will increment the _"Files Skipped"_ counter

I suspect only 1 file on that folder was flagged, because both `kodi-strm` and the Kodi Add-on skipped that 1 file.

**Comment by domdee7** [comment]
Oops, I misclicked the close issue button, sorry...

**Comment by notsatan** [comment]
Just tested this out on my end, there seems to be no problem with the script so far

![Screenshot](https://user-images.githubusercontent.com/22884507/161442142-c84a9d97-4201-483c-b44d-1662e5070ed3.png)

And, the file count matches against what `rclone` gives me for that directory - again leading me to believe that the script is working fine, even to scan larger directories.

As a last resort, can you try fetching the script from `feature/logs` branch instead of `master`
```sh
git clone --branch=feature/logs https://github.com/notsatan/kodi-strm/
```

To generate logs, simply add the argument `--logging`/`--unsafe-logging` to your command when you run `strm-generator.py`. 

```sh
python strm-generator.py --source=<source-id> --unsafe-logging
```

Using any of these flags will dump log output on stdout, and to text file - "*logs.txt*" in your working directory. With logging enabled, the script will log any event of skipping a file, encountering a directory on drive, and creating strm files

Note: Logs generated with `--unsafe-logging` will include file/directory names and other sensitive information (hence "unsafe"). On the other hand, logs generated by the `--logging` flag will use Google Drive folder ID (improved privacy, at the cost of reduced readability)

**Comment by notsatan** [comment]
Hi @domdee7 any updates on this issue with the [`feature/logs`][logs-branch] branch?

[logs-branch]: https://github.com/notsatan/kodi-strm/tree/feature/logs
