### ISSUE TITLE
Add option to update an existing folder

### ISSUE THREAD

**Issue by jaum20** [notsatan/kodi-strm#389]
**Is your feature request related to a problem? Please describe.**
If new files are added to a folder I have already scanned, the scrips asks confirmation for wipe. I would like it do add .strm for the new files keeping the .strm already in the folder.

Example:

if I have this directory structure

/tv_show_(2010)/
 /S01/
  /E01.strm

Eventually S02 will be added to the google drive folder. If I ran the scrit again it will show:

```
Destination directory `/tv_show_(2010)` already exists
Proceed by wiping the existing directory?
```

**Describe the solution you'd like**
An option to just add new strm files wihtout wiping

**Describe alternatives you've considered**

**Comment by notsatan** [comment]
I was thinking of the same sometime around the v2 release — but this change, even if implemented, won't make any noticeable change on the runtime

Even if the target directory is not wiped, `kodi-strm` would still need to go through each file on source drive comparing it's ID with the IDs in the STRM file — this is needed because there is always a possibility that the original file may have been modified even if it has the same name. So it won't be as simple as "skip season 1 folder if it exists" — more like "if season 1 folder exists, traverse it at the same time both on Google drive and on local disk, while comparing each file present, in case of any differences, correct the local copy to match what's there on drive"

Because of this, the overall number of API calls made will remain the same, the same would apply to disk operations as well — each STRM file would need to be read and compared to ensure it still points to the same file, on top of that, the file would need to be wiped and re-written for any changes that may have occurred!

On the downside this would be a lot of code that needs to be written, and maintained over time — for near zero gains! On the flip-side, it's very much easier to simply wipe the existing local directory and create everything from scratch, though it may _seem_ like the existing approach is a waste of resources — its not!

**Comment by notsatan** [comment]
If your intention is to avoid the prompt that's being displayed, you can always use the `--force` flag ([docs][cmd-docs]) to skip the prompt and `kodi-strm` will proceed to directly wipe the contents and continue as usual

[cmd-docs]: https://github.com/notsatan/kodi-strm#quick-overview

**Comment by notsatan** [comment]
Closing this since there's not much that can be done! Feel free to re-open if you have any suggestions on how this can be improved
